test:
    script
sudo: false
python:
  - "2.7"
language: python
install:
    - pip install flask
    - pip install codecov
    - pip install coveralls
script: nosetests --with-coverage --cover-package=flask_extras
after_success:
    - coveralls
    - codecov
